title: Jake Holmquist # your name (or website title) here
logo: "/images/profile-round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Developing High Performing Technical Teams and Leading Digital Transformation. 
  <br><br>
  New York, NY 
  <br><br>
  <a href="https://www.linkedin.com/in/jakedholmquist/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-144829027-2 # your Google Analytics tracking ID here
